version: "3.9"
services:
  api:
    image: ghcr.io/s1ntaxe770r/gopher-quotes-api:latest
    ports:
      #host:container
      - "8080:8080"
    environment:
      - DB_URI=postgresql://rootgopher:gophersbecool@db
    depends_on:
      - db
    expose:
      - 8080
    networks:
      - database 
      - quotes
  db:
    image: postgres:9.6.17-alpine
    environment:
      - POSTGRES_PASSWORD=gophersbecool
      - POSTGRES_USER=rootgopher
    ## should only be available to` api and not on the host
    expose:
      - 5432
    networks:
      - database
  frontend:
    image: ghcr.io/s1ntaxe770r/gopher-quotes-frontend:latest
    ports:
      - "3000:8080"
    environment:
      - QUOTES_API_URL=http://api:8080/quotes
    networks:
      - quotes
  stats:
    image: ghcr.io/s1ntaxe770r/gopher-quotes-stats:latest
    ports:
      - "4000:8080"
    environment:
      - QUOTES_API_URL=http://api:8080/stats
    networks:
      - quotes

networks:
  database:
  quotes:
