apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopher-quotes-frontend
spec:
  selector:
    matchLabels:
      app: gopher-quotes-frontend
  template:
    metadata:
      labels:
        app: gopher-quotes-frontend
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'gopher-quotes-api:8080'
    spec:
      containers:
      - name:  gopher-quotes-frontend
        image: ghcr.io/s1ntaxe770r/gopher-quotes-frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        env:
        - name: "QUOTES_API_URL"
          value: http://localhost:8080/quotes
        ports:
        - containerPort: 4040
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopher-quotes-api
spec:
  selector:
    matchLabels:
      app: gopher-quotes-api
  template:
    metadata:
      labels:
        app: gopher-quotes-api
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      containers:
      - name:  gopher-quotes-api
        image: ghcr.io/s1ntaxe770r/gopher-quotes-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        env:
        - name: "DB_URI"
          value: postgresql://rootgopher:gophersbecool@postgres:5432
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopher-quote-stats
spec:
  selector:
    matchLabels:
      app: gopher-quote-stats 
  template:
    metadata:
      labels:
        app: gopher-quote-stats
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'gopher-quotes-api:8080'
    spec:
      containers:
      - name:  gopher-quotes-stats
        image: ghcr.io/s1ntaxe770r/gopher-quotes-stats:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        env:
        - name: "QUOTES_API_URL"
          value: http://localhost:8080/stats
        ports:
        - containerPort: 8081
