apiVersion: v1
kind: Service
metadata:
  name: gopher-quotes-api
spec:
  selector:
    app: gopher-quotes-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gopher-quotes-frontend
spec:
  selector:
    app: gopher-quotes-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: gopher-quote-stats
spec:
  selector:
    app: gopher-quote-stats
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
